import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@stream-io/video-react-sdk/dist/css/styles.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/toaster";
import "./globals.css";
import "react-datepicker/dist/react-datepicker.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <ClerkProvider
        appearance={{
          variables: {
            colorText: "#000",
            colorPrimary: "#0E78F9",
            colorBackground: "#f1f5f9",
            colorInputBackground: "#f1f5f9",
            colorInputText: "#000",
          },
        }}
      >
        <body className={`${inter.className} `}>
          {children}
          <Toaster />
        </body>
      </ClerkProvider>
    </html>
  );
}
